### PR TITLE
Update example-requirements.txt

### PR DESCRIPTION
**Pull request by SUSHMITAH**

### CODE REVIEW

**Comment by rene-aguirre** [comment]
@SUSHMITAH  What is the purpose for this patch?

**Comment by SUSHMITAH** [comment]
Hi René,

I see that the pull request has been closed. Any specific reasons, please?
Also I would need the patch to access PCIe configuration space registers
(BAR) on Windows system.

*Thanks and regards,*
*Sushmitha R*

**Comment by rene-aguirre** [comment]
How the patches are relevant for PCIe access?

the `example-requirements.txt` file was just intended to hint that other packages might be used to interact with the examples.

Kind of a pseudo `pip` `requirements.txt`.

What is the purpose of the patch? Can you give more details in the line changes? how the library users are expected to use it?

Provided it makes sense (even for reference if anyone needs your patch regardless of merge), it would be better if you consolidate both line changes in a single pull request.

**Comment by SUSHMITAH** [comment]
Hi,

I'm looking to read the VID and DID of connected devices from the PCIe BAR
registers to store the IDs for comparison with another BOM. I came across
your patches and was looking to see if there could be a help to read the
same from your side.
I am also a novice in using Github. My aplogies if any of the questions
seem to be not on Github terms.

*Thanks and regards,*
*Sushmitha R*

**Comment by rene-aguirre** [comment]
@SUSHMITAH This library is not suitable for HAL like access to PCIe BAR information.

Take a look so the Windows SDK documentation, example: https://docs.microsoft.com/en-us/windows-hardware/drivers/pci/

I'm still puzzled on what is your intend this line:
    device manager hardware id list

can you explain the change?

**Comment by SUSHMITAH** [comment]
Hi Rene,

Under device manager, if the hardware ID of any connected device is checked
it gives out both PID and DID information.
On similar lines I was looking for a Python wrapper that would give me such
info.
I am currently trying to map only PCI devices.Hence I wanted to probe PCIe
BAR.

*Thanks and regards,*
*Sushmitha R*

**Pull request closed without merging**
